version: '3.8'
services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: festival
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/test/resources/testdb/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/test/resources/testdb/data.sql:/docker-entrypoint-initdb.d/2-data.sql
