spring:
  application:
    name: festival

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true



auth:
  password: ${ADMIN_PASSWORD}

# Firebase 설정
firebase:
  service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}

springdoc:
  use-fqn: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
#            extract: TRACE #조회 값까지 보고 싶으면

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expire-length: ${JWT_EXPIRE_LENGTH:86400000}